[project]
name = "anime-downloader"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aria2p>=0.12.1",
    "brotli>=1.2.0",
    "bs4>=0.0.2",
    "lxml>=6.1.1",
    "m3u8>=6.0.0",
    "pycryptodome>=3.23.0",
    "typer>=0.26.7",
    "yt-dlp>=2026.6.9",
]

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
